runtime: nodejs10
env: flex
service: eletronicstore

handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html
- url: /
  static_dir: build
  http_headers:
    Access-Control-Allow-Origin: "*"
- url: /.*
  script: auto
  secure: always